config/routes.rb
TravelHelper::Application.routes.draw do

  
  resources :plan do
    resources :plan_details
  end
  
  resources :plan_details

  devise_for :users

  root :to => 'static_pages#home'
  match '/my', to: 'static_pages#my'
  

end

app/models/plan.rb
# == Schema Information
#
# Table name: plans
#
#  id          :integer(4)      not null, primary key
#  title       :string(255)     计划名称
#  username    :string(255)     用户名
#  connect     :string(255)     联系方式-
#  password    :string(255)     浏览密码
#  gonglue_url :string(255)     所属的攻略地址，方便穷游及马蜂窝的用户-
#  user_id     :integer(4)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Plan < ActiveRecord::Base
  belongs_to :user
  has_many :plan_details, dependent: :destroy 
  attr_protected :user_id
  
  validates :title, :presence => true
end

app/models/plan_detail.rb
# == Schema Information
#
# Table name: plan_details
#
#  id          :integer(4)      not null, primary key
#  type        :string(255)     存储类型：飞机，住，吃，路线安排
#  from_city   :string(255)     起飞城市
#  to_city     :string(255)     抵达城市
#  go_time     :date            起飞时间/入住时间
#  arrive_time :date            到达时间/离店时间
#  price       :integer(4)      价格
#  hotel_name  :string(255)     酒店名称
#  note        :string(255)     备注，限制150个字符，需要精华
#  zoufa       :text            具体走法，如怎样到达酒店
#  plan_id     :integer(4)      
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class PlanDetail < ActiveRecord::Base
  attr_protected :type
  
  belongs_to :plan
  
  default_scope order: 'plan_details.go_time'
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  validates :username, :presence => true
  
  has_many :plans, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/plan_controller.rb
# coding: utf-8
class PlanController < ApplicationController
  before_filter :authenticate_user! , :except => [ :show,:index ]
  
  def index
    @plans = Plan.all
  end
  
  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(params[:plan])
    @plan.username = current_user.username
    @plan.user_id = current_user.id

    if @plan.save
      redirect_to new_plan_plan_detail_path(@plan)
    else
      render 'new'
    end
  end
  
  def edit
    @plan = Plan.find(params[:id])
  end
  
  def show
    @plan = Plan.find(params[:id])
    @page_title = @plan.title
    @plan_details = @plan.plan_details
    @total_air_price = @plan_details.where(plan_type: "air").sum(:price).to_f
    @total_hotel_price = @plan_details.where(plan_type: "hotel").sum(:price).to_f
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update_attributes(params[:plan])
      flash[:success] = "更新成功."
      redirect_to plan_path(@plan)
    end
  end

  def destroy
    Plan.find(params[:id]).destroy
    flash[:success] = "删除成功."
    redirect_to my_path
  end
  
end

app/controllers/plan_details_controller.rb
# coding: utf-8
class PlanDetailsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @plan = Plan.find(params[:plan_id])
    @plan_details = @plan.plan_details.build
  end

  def create
    @plan = Plan.find(params[:plan_id])
        
    params[:plan_detail_air].each do |i, values|
      u = PlanDetail.new(values)
      u.plan_id = @plan.id
      u.plan_type = "air"      
      u.save if the_row_not_null(values)
    end
    
    params[:plan_detail_hotel].each do |i, values|
      u = PlanDetail.new(values)
      u.plan_id = @plan.id
      u.plan_type = "hotel"
      u.save if the_row_not_null(values)
    end
    
    params[:plan_detail_way].each do |i, values|
      u = PlanDetail.new(values)
      u.plan_id = @plan.id
      u.plan_type = "way"
      u.save if the_row_not_null(values)
    end
    
    update_total_price(@plan)
    
    redirect_to plan_path(@plan)
    
  end
  
  def edit
    @detail = PlanDetail.find(params[:id])
    render layout:false
  end

  def update
    detail = PlanDetail.find(params[:id])
    
    if detail.update_attributes(params[:plan_detail])
      plan = Plan.find(detail.plan_id)
      update_total_price(plan)
      
      flash[:success] = "修改成功"
      redirect_to plan_path(detail.plan_id)
    end
  end

  def destroy
    PlanDetail.find(params[:id]).destroy
    flash[:success] = "删除成功."
    redirect_to :back
  end

private

  def the_row_not_null(values)
    num = 0
    
    values.each do |v,value|
      unless value.blank?
        num += 1
      end
      
      if num == 0
        return false
      end
    end
  end
  
  def update_total_price(plan)
    @plan = plan
    @total_price = @plan.plan_details.sum(:price).to_f
    @plan.update_attributes(price:@total_price)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def my
    @plans = current_user.plans
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    flash_messages = []

    flash.each do |type, message|
      type = "alert-success" if type == :notice
      type = "alert-success" if type == :success
      text = content_tag(:div, link_to("x", "#", :class => "close", 'data-dismiss' => 'alert') + message, :class => "alert #{type}")
      flash_messages << text if message
    end

    flash_messages.join("\n").html_safe
  end
  
  def render_page_title
    title = @page_title ? "#{@page_title} | #{SITE_NAME}" : SITE_NAME rescue "SITE_NAME"
    content_tag("title", title, nil, false)
  end
end

app/helpers/plan_details_helper.rb
module PlanDetailsHelper
end

app/helpers/plan_helper.rb
module PlanHelper
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/common/_user_nav.html.erb
<% if current_user %>

  <%= render_list :class => "nav" do |li|
    li << link_to("管理我的行程",    my_path)
  end %>

  <%= render_list :class => "nav pull-right" do |li|
    li << link_to("个人资料",    edit_user_registration_path)
    li << link_to("退出", destroy_user_session_path, :method => :delete)
  end %>
  
<% else %>
  <%= render_list :class => "nav pull-right" do |li|
    li << link_to("登陆",    new_user_session_path)
    li << link_to("注册", new_user_registration_path)
  end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title %>
  <%= stylesheet_link_tag    "application", media: "screen" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!–[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]–>
</head>
<body>
  <% if !current_page?(root_path) %>
  <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <%= link_to "行程单", '/', id: "logo" %>
            <nav>
              <%= render "common/user_nav" %>
            </nav>
          </div>
        </div>
      </header>
  <% end %>
  <div class="container">
    <%= notice_message %>
    
    <%= yield %>
    
    <footer class="footer" style="text-align: center;">
      <p>
        © 2012 行程单 Development by <a href="http://weibo.com/zhangyiqun1" target="_blank">zhangyiqun.</a>
      </p>
    </footer>

  </div>
  


</body>
</html>

app/views/plan/_plan_form.html.erb
<%= render "shared/error_messages", :target => @plan %>

<div class="control-group">
  <%= f.label :title ,:class=> "control-label" %>
  <div class="controls">
    <%= f.text_field :title ,:class=> "input-xlarge"%>
  </div>
</div>

<div class="control-group">
  <%= f.label :password ,:class=> "control-label" %>
  <div class="controls">
    <%= f.password_field :password ,:class=> "input-xlarge"%>
    <span class="help-block">如需加密请填写密码，否则留空</span>
  </div>
</div>

app/views/plan/create.html.erb
<h1>Plan#create</h1>
<p>Find me in app/views/plan/create.html.erb</p>

app/views/plan/destroy.html.erb
<h1>Plan#destroy</h1>
<p>Find me in app/views/plan/destroy.html.erb</p>

app/views/plan/edit.html.erb
<%= form_for(@plan,url: plan_path ,:html =>{:class => "form-horizontal well"}) do |f| %>
  <fieldset>
    <legend>编辑行程单</legend>
    
    <%= render :partial => 'plan_form', :locals => { :f => f } %>
    
    <div class="form-actions">
      <%= f.submit "保存",:class => "btn btn-primary" %>
      <%= link_to "添加行程安排",new_plan_plan_detail_path(@plan),:class=>"btn" if current_user%>
    </div>
  </fieldset>
<% end %>

app/views/plan/index.html.erb
<% if @plans.any? %>
<div class="well">
  <table class="table">
    <thead>
      <tr>
        <th>名称</th>
        <th>总计花费</th>
        <th>更新时间</th>
      </tr>
    </thead>
    <tbody>
      <% @plans.each do |plan| %>
      <tr>
        
        <td><%= link_to plan.title,plan_path(plan) %></td>
        <td><%= plan.price %></td>
        <td><%= plan.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></td>

      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/plan/new.html.erb
<%= form_for(@plan,url: plan_index_path ,:html =>{:class => "form-horizontal well"}) do |f| %>
  <fieldset>
    <legend>新建行程单</legend>
    
    <%= render :partial => 'plan_form', :locals => { :f => f } %>
    
    <div class="form-actions">
      <%= f.submit "下一步",:class => "btn btn-primary" %>
      <a class="btn" href="/my">取消</a>
    </div>
  </fieldset>
<% end %>

app/views/plan/show.html.erb
<div class="alert">
  <div class="plan_detail_head">
    <h2><%= @plan.title%></h2>
    <span>由 <%= @plan.username%>
    于 <%= @plan.created_at.strftime("%Y-%m-%d %T")%> 时创建。</span>
    <br>
    
    <%= link_to "编辑",edit_plan_path(@plan),:class=>"btn btn-mini" if current_user%>
    <%= link_to "添加行程安排",new_plan_plan_detail_path(@plan),:class=>"btn btn-mini" if current_user%>
  </div>
</div>

<div class="modal fade" id="edit-plan-detail-modal" style="width:690px;">

</div>

<div class="well">

  <div class="alert alert-info">
    总计花费：<%= number_to_currency(@plan.price, :unit => "")%>元。
    其中交通工具花费了<%= number_to_currency(@total_air_price, :unit => "")%>元，
    住花费了<%= number_to_currency(@total_hotel_price, :unit => "")%>元。
  </div>

  <span class="label label-info" style="font-size:15px"><i class="icon-plane icon-white icon-add-margin"></i>飞机</span>

  <table class="table">
    <thead>
      <tr>
        <th>启程</th>
        <th>抵达</th>
        <th>启程时间</th>
        <th>到达时间</th>
        <th>价格(元)</th>
      </tr>
    </thead>
    <tbody>
      <% @plan_details.each do |detail| %>
        <% if detail.plan_type == "air"%>
          <tr>
            <td><%= detail.from_city%></td>
            <td><%= detail.to_city%></td>
            <td><%= detail.go_time.try(:strftime,"%Y-%m-%d %H:%M")%></td>
            <td><%= detail.arrive_time.try(:strftime,"%Y-%m-%d %H:%M")%></td>
            <td><%= detail.price%></td>
            <% if current_user %>
              <td>
                <a class="btn btn-mini edit-plan-detail" href="javascript: void(0)" id="<%= edit_plan_detail_path(detail) %>">修改</a>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <span class="label label-warning" style="font-size:15px"><i class="icon-home icon-white icon-add-margin"></i>住宿</span>

  <table class="table">
    <thead>
      <tr>
        <th>所在城市</th>
        <th>酒店名称</th>
        <th>入住日期</th>
        <th>离店日期</th>
        <th>价格(元)</th>
      </tr>
    </thead>
    <tbody>
      <% @plan_details.each do |detail| %>
        <% if detail.plan_type == "hotel"%>
          <tr>
            <td><%= detail.to_city%></td>
            <td><%= detail.hotel_name%></td>
            <td><%= detail.go_time.try(:strftime,"%Y-%m-%d %H:%M")%></td>
            <td><%= detail.arrive_time.try(:strftime,"%Y-%m-%d %H:%M")%></td>
            <td><%= detail.price%></td>
            <% if current_user %>
              <td>
                <a class="btn btn-mini edit-plan-detail" href="javascript: void(0)" id="<%= edit_plan_detail_path(detail) %>">修改</a>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <span class="label label-success" style="font-size:15px"><i class="icon-map-marker icon-white icon-add-margin"></i>路线规划</span>

  <table class="table">
    <thead>
      <tr>
        <th>出发地</th>
        <th>目标</th>
        <th>出发时间</th>
        <th>详细</th>
      </tr>
    </thead>
    <tbody>
      <% @plan_details.each do |detail| %>
        <% if detail.plan_type == "way"%>
          <tr>
            <td><%= detail.from_city%></td>
            <td><%= detail.to_city%></td>
            <td><%= detail.go_time.try(:strftime,"%Y-%m-%d %H:%M")%></td>
            <td style="width: 360px;"><p style="width:350px;word-wrap: break-word;"><%= detail.zoufa %><p></td>
            <% if current_user %>
              <td>
                <a class="btn btn-mini edit-plan-detail" href="javascript: void(0)" id="<%= edit_plan_detail_path(detail) %>">修改</a>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>


<!-- Duoshuo Comment BEGIN -->
	<div class="ds-thread"></div>
	<script type="text/javascript">
	var duoshuoQuery = {short_name: "xingcheng"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = 'http://static.duoshuo.com/embed.js';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- Duoshuo Comment END -->

app/views/plan/update.html.erb
<h1>Plan#update</h1>
<p>Find me in app/views/plan/update.html.erb</p>

app/views/plan_details/_air.html.erb
<div class="control-group" id="1">
  <%= text_field_tag "plan_detail[from_city]",nil, :class => "input-small",value:@detail.from_city,placeholder:"起飞城市"%>
  <%= text_field_tag "plan_detail[to_city]",nil, :class => "input-small",value:@detail.to_city,placeholder:"抵达城市" %>
  <%= text_field_tag "plan_detail[go_time]",nil, :class => "input-medium picktime",value:@detail.go_time,readonly:"readonly",placeholder:"起飞时间" %>
  <%= text_field_tag "plan_detail[arrive_time]",nil, :class => "input-medium picktime",value:@detail.arrive_time,readonly:"readonly",placeholder:"到达时间" %>
  <%= text_field_tag "plan_detail[price]",nil, :class => "input-small",value:@detail.price,placeholder:"价格:人民币" %>
</div>

app/views/plan_details/_hotel.html.erb
<div class="control-group" id="1">
  <%= text_field_tag "plan_detail[to_city]",nil, :class => "input-small",placeholder:"所在城市",value:@detail.to_city %>
  <%= text_field_tag "plan_detail[hotel_name]",nil, :class => "input-small",placeholder:"酒店名称",value:@detail.hotel_name %>
  <%= text_field_tag "plan_detail[go_time]",nil, :class => "input-medium picktime-sample",placeholder:"入住日期",readonly:"readonly",value:@detail.go_time %>
  <%= text_field_tag "plan_detail[arrive_time]",nil, :class => "input-medium picktime-sample",placeholder:"离店日期",readonly:"readonly",value:@detail.arrive_time %>
  <%= text_field_tag "plan_detail[price]",nil, :class => "input-small",placeholder:"含税总价",value:@detail.price %>
</div>

app/views/plan_details/_way.html.erb
<div class="control-group" id="1">
  <%= text_field_tag "plan_detail[from_city]",nil, :class => "input-medium",placeholder:"从(XX机场)",value:@detail.from_city %>
  <%= text_field_tag "plan_detail[to_city]",nil, :class => "input-medium",placeholder:"至(XX酒店)",value:@detail.to_city %>
  <%= text_field_tag "plan_detail[go_time]",nil, :class => "input-medium picktime-sample",placeholder:"时间",value:@detail.go_time %>
  <%= text_area_tag "plan_detail[zoufa]",@detail.zoufa, :class => "input-xlarge zoufa",placeholder:"走法" %>
</div>

app/views/plan_details/create.html.erb
<%= @total_price%>

app/views/plan_details/destroy.html.erb
<h1>PlanDetails#destroy</h1>
<p>Find me in app/views/plan_details/destroy.html.erb</p>

app/views/plan_details/edit.html.erb
<%#TODO%>
<script>
(function() {

  jQuery(function() {
    var insertNewLine, number, show_line;
    $("#add_air_button").click(function() {
      return show_line("#add_air");
    });
    $("#add_hotel_button").click(function() {
      return show_line("#add_hotel");
    });
    $("#add_way_button").click(function() {
      return show_line("#add_way");
    });
    show_line = function(the_div) {
      return $(the_div).parent().children().each(function() {
        if ($(this).is(":hidden")) {
          $(this).show();
          return false;
        }
      });
    };
    insertNewLine = function(the_button_div) {
      var line_num, new_line, new_line_num, the_node;
      the_node = $(the_button_div).prev();
      line_num = parseInt(the_node.attr("id"));
      new_line_num = line_num + 1;
      new_line = the_node.clone();
      new_line.attr("id", new_line_num);
      new_line.children().each(function() {
        var new_id, new_name;
        new_id = $(this).attr("id").replace(line_num, new_line_num);
        new_name = $(this).attr("name").replace(line_num, new_line_num);
        $(this).attr("id", new_id);
        $(this).attr("name", new_name);
        return $(this).attr("value", "");
      });
      $(the_button_div).before(new_line);
      return new_line.hide();
    };
    for (number = 1; number <= 15; number++) {
      insertNewLine("#add_air");
      insertNewLine("#add_hotel");
      insertNewLine("#add_way");
    }
    $(".picktime").datetimepicker({
      numberOfMonths: 1,
      showButtonPanel: true,
      dateFormat: 'yy-mm-dd',
      clearText: "清除",
      closeText: "关闭",
      yearSuffix: '年',
      showMonthAfterYear: true,
      monthNames: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
      dayNames: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
      dayNamesShort: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
      dayNamesMin: ['日', '一', '二', '三', '四', '五', '六']
    });
    return $(".picktime-sample").datepicker({
      numberOfMonths: 1,
      showButtonPanel: true,
      dateFormat: 'yy-mm-dd',
      clearText: "清除",
      closeText: "关闭",
      yearSuffix: '年',
      showMonthAfterYear: true,
      monthNames: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
      dayNames: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
      dayNamesShort: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
      dayNamesMin: ['日', '一', '二', '三', '四', '五', '六']
    });
  });

}).call(this);

</script>

<div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
  <h3>修改</h3>
</div>

<%= form_tag(plan_detail_path(@detail), :method => "put") do %>
  <div class="modal-body">
  
    <%= render @detail.plan_type%>
  
  </div>
  
  <div class="modal-footer">
    <%= link_to "删除",plan_detail_path(@detail),:class => "btn btn-danger",method: :delete, confirm: "确定?" %>
    <button type="submit" class="btn btn-primary">保存</button>
  </div>
<% end %>

app/views/plan_details/new.html.erb
<div class="alert alert-info">
  在此填写详细的行程安排
</div>

<%= form_for(@plan_details,url: plan_plan_details_path(@plan) ,:html =>{:class => "well",id:"all_plan_detail_air"}) do |f| %>
  <fieldset>
    <legend class="no-margin-bottom">飞机</legend>

    <div class="control-group" id="1">
      <%= text_field_tag "plan_detail_air[1][from_city]",nil, :class => "input-small",placeholder:"起飞城市"%>
      <%= text_field_tag "plan_detail_air[1][to_city]",nil, :class => "input-small",placeholder:"抵达城市" %>
      <%= text_field_tag "plan_detail_air[1][go_time]",nil, :class => "input-medium picktime",placeholder:"起飞时间" %>
      <%= text_field_tag "plan_detail_air[1][arrive_time]",nil, :class => "input-medium picktime",placeholder:"到达时间",readonly:"readonly" %>
      <%= text_field_tag "plan_detail_air[1][price]",nil, :class => "input-small",placeholder:"价格:人民币" %>
    </div>
    
    <div class="control-group" id="add_air">
      <a id="add_air_button" class="btn btn-info" href="javascript:void(0)">增加</a>
    </div>
    
  </fieldset>
  
  <fieldset>
    <legend class="no-margin-bottom">住宿</legend>

    <div class="control-group" id="1">
      <%= text_field_tag "plan_detail_hotel[1][to_city]",nil, :class => "input-small",placeholder:"所在城市" %>
      <%= text_field_tag "plan_detail_hotel[1][hotel_name]",nil, :class => "input-small",placeholder:"酒店名称" %>
      <%= text_field_tag "plan_detail_hotel[1][go_time]",nil, :class => "input-medium picktime-sample",placeholder:"入住日期",readonly:"readonly" %>
      <%= text_field_tag "plan_detail_hotel[1][arrive_time]",nil, :class => "input-medium picktime-sample",placeholder:"离店日期",readonly:"readonly" %>
      <%= text_field_tag "plan_detail_hotel[1][price]",nil, :class => "input-small",placeholder:"含税总价" %>
    </div>
    
    <div class="control-group" id="add_hotel">
      <a id="add_hotel_button" class="btn btn-info" href="javascript:void(0)">增加</a>
    </div>
    
  </fieldset>
  
  <fieldset>
    <legend class="no-margin-bottom">路线规划</legend>

    <div class="control-group" id="1">
      <%= text_field_tag "plan_detail_way[1][from_city]",nil, :class => "input-medium",placeholder:"从(XX机场)" %>
      <%= text_field_tag "plan_detail_way[1][to_city]",nil, :class => "input-medium",placeholder:"至(XX酒店)" %>
      <%= text_field_tag "plan_detail_way[1][go_time]",nil, :class => "input-medium picktime-sample",placeholder:"出发时间" %>
      <%= text_area_tag "plan_detail_way[1][zoufa]",nil, :class => "input-xlarge zoufa",placeholder:"走法" %>
    </div>
    
    <div class="control-group" id="add_way">
      <a id="add_way_button" class="btn btn-info" href="javascript:void(0)">增加</a>
    </div>
    
  </fieldset>
  
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">保存</button>
    <a class="btn" href="<%= my_path %>">取消</a>
  </div>
<% end %>

app/views/plan_details/update.html.erb
<h1>PlanDetails#update</h1>
<p>Find me in app/views/plan_details/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
 <div class="alert alert-error">
   <a class="close" data-dismiss="alert">×</a>
   <p><strong>有 <%= target.errors.count %> 处问题导至无法提交:</strong></p>
   <ul>
   <% target.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>

app/views/static_pages/home.html.erb
<header class="jumbotron masthead">
  <div class="inner">
    <h1>行程单</h1>
    <p>为不爱看冗长攻略的人而生，一张只有吃喝住行的单子</p>
    <p class="download-info">
      <a href="/plan/new" class="btn btn-primary btn-large">分享我的行程</a>
      <a href="/plan" class="btn btn-large">看别人的行程</a>
    </p>
  </div>

  <div class="bs-links">
    <ul class="quick-links">
      <li><a href="#">关于</a></li>
    </ul>
  </div>
</header>

app/views/static_pages/my.html.erb
<style>
body{background-image:none;}
</style>
<h2>管理行程</h2>

<div style="margin-bottom: 18px;">
<a class="btn btn-primary" href="<%= new_plan_path%>">添加</a>
</div>

<% if @plans.any? %>
<div class="well">
  <table class="table">
    <thead>
      <tr>
        <th>名称</th>
        <th>总计花费</th>
        <th>更新时间</th>
      </tr>
    </thead>
    <tbody>
      <% @plans.each do |plan| %>
      <tr>
        
        <td><%= link_to plan.title,plan_path(plan) %></td>
        <td><%= plan.price %></td>
        <td><%= plan.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        
        <td>
          <%= link_to "修改",edit_plan_path(plan),:class => "btn" %>
          <%= link_to "删除",plan_path(plan),:class => "btn btn-danger",method: :delete, confirm: "确定?" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>